workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest  # Note: This should be at same level as 'environment'
    scripts:
      - flutter gen-l10n
      - flutter pub get
      - flutter build ios --simulator
      - mkdir -p build/ios/ipa
      - zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip